In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import urllib.request
from bs4 import BeautifulSoup

In [10]:
def GetData(ym,lawd_cd):
    API_KEY = "jWXW%2B4GCUF1VfkIcLuEHXjvrX8LBrA9TT3nAv6a6nnNkZvGmTxizW4y15TpD5TVaFnfEeT2%2B226vVpZ8KblY6A%3D%3D"
    
    url = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD={loc}&DEAL_YMD={date}&serviceKey={key}"
    url = url.format(loc=lawd_cd, date=ym, key=API_KEY)

    result = urllib.request.urlopen(url).read().decode("utf-8")
    xmlsoup = BeautifulSoup(result, 'lxml-xml')

    te=xmlsoup.findAll("item")

    df_temp=pd.DataFrame()


    for t in te:
        build_y=t.find("건축년도").text
        year=t.find("년").text
        month=t.find("월").text
        day=t.find("일").text
        dong=t.find("법정동").text
        price=t.find("거래금액").text
        apt_nm=t.find("아파트").text
        size=t.find("전용면적").text

        try:
            jibun=t.find("지번").text
        except:
            jibun=""

        ji_code=t.find("지역코드").text
        floor=t.find("층").text

        temp = pd.DataFrame(([[build_y,year,month,day,dong,price,apt_nm,size,jibun,ji_code,floor]]), columns=["build_y","year","month","day","dong","price","apt_nm","size","jibun","ji_code","floor"])
        df_temp=pd.concat([df_temp,temp])

    df_temp=df_temp.reset_index(drop=True)

    return df_temp

In [2]:
import pandas as pd
#https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=66732
code=pd.read_excel("../data/KIKcd_B.20181105.xlsx")

code_seo=code[(code["시도명"]=="대전광역시")]

code_seo=code_seo[code_seo["읍면동명"].isnull()==True]

code_seo = code_seo[code_seo["시군구명"].isnull() == False]

code_seo["ji_code"] = code_seo["법정동코드"].astype(str).str[0:5]

In [4]:
code_seo

           법정동코드    시도명 시군구명 읍면동명  동리명      생성일자  말소일자 ji_code
1573  3011000000  대전광역시   동구  NaN  NaN  19950101   NaN   30110
1619  3014000000  대전광역시   중구  NaN  NaN  19950101   NaN   30140
1646  3017000000  대전광역시   서구  NaN  NaN  19950101   NaN   30170
1674  3020000000  대전광역시  유성구  NaN  NaN  19950101   NaN   30200
1728  3023000000  대전광역시  대덕구  NaN  NaN  19950101   NaN   30230